-- ============================================================================
-- Big Bang Immigration CRM - Seed data
-- Runs after migrations on `supabase db reset` (or via `npm run db:reset`).
--
-- Reference data (countries, document categories, service types, templates,
-- template documents) is now owned by the migrations themselves:
--   - 20260501000001_initial_schema.sql (categories, services, templates)
--   - 20260512000001_seed_countries.sql (countries)
-- so that every environment — local AND remote — gets the same rows at
-- deploy time (supabase db push skips this seed directory).
--
-- This file is intentionally left empty; keep it in place in case
-- environment-specific demo data is ever needed.
-- ============================================================================
