"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import { getAgent } from "@/lib/auth/agent";
import { createClient } from "@/lib/supabase/server";

const optionalText = (max: number) =>
  z.preprocess(
    (v) => {
      if (v === null || v === undefined) return undefined;
      if (typeof v === "string" && v.trim() === "") return undefined;
      return v;
    },
    z.string().max(max).optional(),
  );

const registerClientSchema = z.object({
  legal_name_full: z
    .string()
    .trim()
    .min(1, "Full legal name is required")
    .max(200),
  email: z.preprocess(
    (v) => (typeof v === "string" && v.trim() !== "" ? v.trim() : undefined),
    z.string().email("Enter a valid email").optional(),
  ),
  phone_primary: optionalText(50),
  country_of_citizenship: z.preprocess(
    (v) => (typeof v === "string" && v.trim() !== "" ? v : undefined),
    z.string().length(2).optional(),
  ),
  country_of_residence: z.preprocess(
    (v) => (typeof v === "string" && v.trim() !== "" ? v : undefined),
    z.string().length(2).optional(),
  ),
  notes: optionalText(2000),
});

export type RegisterClientResult =
  | { ok: true; id: string }
  | { error: string; fieldErrors?: Record<string, string[]> };

export async function registerClient(
  payload: unknown,
): Promise<RegisterClientResult> {
  const agent = await getAgent();
  if (!agent) return { error: "Not authorized" };

  const parsed = registerClientSchema.safeParse(payload);
  if (!parsed.success) {
    return {
      error: "Please fix the errors below.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<
        string,
        string[]
      >,
    };
  }

  const supabase = await createClient();

  // client_number is generated by a SQL function; the authenticated role (which
  // agents are) holds EXECUTE + sequence USAGE.
  const { data: clientNumber, error: numErr } = await supabase
    .schema("crm")
    .rpc("generate_client_number");
  if (numErr || !clientNumber) {
    return { error: numErr?.message ?? "Could not generate a client number" };
  }

  // created_by_agent is also force-set by the scrub trigger, but we set it here
  // so the row matches clients_agent_insert WITH CHECK and the RETURNING select
  // (clients_agent_select) returns the new row.
  const { data: created, error: insertErr } = await supabase
    .schema("crm")
    .from("clients")
    .insert({
      client_number: clientNumber as unknown as string,
      legal_name_full: parsed.data.legal_name_full,
      email: parsed.data.email ?? null,
      phone_primary: parsed.data.phone_primary ?? null,
      country_of_citizenship: parsed.data.country_of_citizenship ?? null,
      country_of_residence: parsed.data.country_of_residence ?? null,
      notes: parsed.data.notes ?? null,
      created_by_agent: agent.id,
    })
    .select("id")
    .single();

  if (insertErr || !created) {
    return { error: insertErr?.message ?? "Could not register the client" };
  }

  revalidatePath("/portal");
  return { ok: true, id: created.id };
}
